services:
  gitea:
    image:  docker.gitea.com/gitea:latest
    container_name: gitea
    hostname: gitea
    environment:
      - USER_UID=${USER_ID}
      - USER_GID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_database:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_MYSQL_PASSWORD}
      - GITEA__server__ROOT_URL=https://${GITEA_HOSTNAME}/
      - GITEA__server__DOMAIN=${GITEA_HOSTNAME}
      - GITEA__server__HTTP_PORT=3005
      - GITEA__server__SSH_PORT=22
      - GITEA__database__LOG_SQL=false
    volumes:
      - ${DATA_ROOT}/gitea:/data
    ports:
      - "3005:3005"
      - "222:22"
    restart: unless-stopped
    depends_on:
      gitea_database:
        condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`${GITEA_HOSTNAME}`)
      - traefik.http.routers.gitea.tls=true
      - traefik.http.routers.gitea.tls.certresolver=myresolver
      - traefik.http.services.gitea.loadbalancer.server.port=3005
      
  gitea_database:
    image: docker.io/library/postgres:14
    container_name: gitea_database
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${GITEA_MYSQL_PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - ${CONFIG_ROOT:-.}/gitea/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gitea"]
      interval: 10s
      timeout: 5s
      retries: 5
